//CI/BE Jenkinsfile

pipeline {
    agent any

    environment {
        DOCKERHUB_REPO = "ejjem/s14p11a704"
        DOCKER_CREDENTIAL_ID = "DockerHub_Token"
    }

    stages {
            stage('Checkout') {
                steps {
                    checkout scm
                }
            }

        stage('Backend Test') {
            steps {
                dir('backend') { // 디렉토리 이동
                    echo "===== STARTING TESTS ====="
                    sh 'chmod +x gradlew' // 실행 권한 부여
                    sh './gradlew test || echo "Test failed but continuing..." '
                }
            }
        }

        stage('Backend Build') {
            steps {
                dir('backend') { // 디렉토리 이동
                    echo "===== BUILDING JAR ====="
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Copy Config to EC2') {
            steps {
                script {
                    echo "===== COPYING CONFIG TO HOST ====="
                    // env. 를 붙여서 환경 변수에 접근해야 합니다.
                    sh "mkdir -p ${env.TARGET_CONF_DIR}"

                    // 또는 env 없이 따옴표 안에서 바로 쉘 변수로 사용하려면 큰따옴표 대신 작은따옴표를 씁니다.
                    sh 'cp my.cnf ${TARGET_CONF_DIR}/my.cnf'

                    echo "Config file copied to ${env.TARGET_CONF_DIR}/my.cnf"
                }
            }
        }


        stage('Docker Build & Push') {
            steps {
                echo "===== DOCKERIZING ====="
                    script {
                        dir('backend') { // 디렉토리 이동
                            // Docker Build
                            // 태그: backend (고정 태그 사용)
                            sh "docker build -t ${DOCKERHUB_REPO}:backend ."

                            // Docker Login & Push
                            withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIAL_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                            sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                            sh "docker push ${DOCKERHUB_REPO}:backend"
                        }
                        // Clean up local images
                        sh 'docker rmi ejjem/s14p11a704:backend || true'
                    }
                }
            }
        }

        stage('Trigger CD') {
            steps {
                script {
                    echo "===== TRIGGER CD/FINAL ====="
                    // CD 트리거는 디렉토리와 상관없이 수행
                    build job: 'CD/Final',
                        wait: true,
                        parameters: [
                        string(name: 'TARGET_SERVICES', value: 'app'),
                        ]
                }
            }
        }
    }
    post {
        success {
            echo "CI(BE) SUCCESS"
            sh 'date "+%Y-%m-%d %H:%M:%S %Z"'
        }
        failure {
            echo "CI(BE) FAILURE"
            sh 'date "+%Y-%m-%d %H:%M:%S %Z"'
        }
        always {
            echo "CI(BE) DONE"
        }
    }
}