//CI/BE Jenkinsfile

pipeline {
    agent any

    environment {
        DOCKERHUB_REPO = "ejjem/mento-backend"
        DOCKER_CREDENTIAL_ID = "DockerHub_Token"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Test') {
            steps {
                echo "===== STARTING TESTS ====="
                sh './gradlew test'
            }
        }

        stage('Backend Build') {
            steps {
                echo "===== BUILDING JAR ====="
                sh './gradlew clean build -x test'
            }
        }

        stage('Docker Build & Push') {
            steps {
                echo "===== DOCKERIZING ====="
                script {
                    sh "mkdir -p build/logs"
                    
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIAL_ID}", usernameVariable: 'DJIB_USER', passwordVariable: 'DJIB_AUTH')]) {
                         sh "./gradlew jib -Djib.to.auth.username=${DJIB_USER} -Djib.to.auth.password=${DJIB_AUTH} -Djib.to.image=${DOCKERHUB_REPO}"
                    }
                }
            }
        }

        stage('Trigger CD') {
            steps {
                script {
                  echo "===== TRIGGER CD/FINAL ====="
                  echo "TARGET_SERVICES='backend'"

                  build job: 'CD/Final',
                    wait: true,
                    parameters: [
                      string(name: 'TARGET_SERVICES', value: 'backend'),
                    ]
                }
            }
        }
    }

    post {
      success {
        echo "CI(BE) SUCCESS"
        sh 'date "+%Y-%m-%d %H:%M:%S %Z"'
      }
      failure {
        echo "CI(BE) FAILURE"
        sh 'date "+%Y-%m-%d %H:%M:%S %Z"'
      }
      always {
        echo "CI(BE) DONE"
      }
    }

}