server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 중요: 어떤 경로로 들어오든 index.html로 보내라 (React Router가 처리하게)
        try_files $uri $uri/ /index.html;
    }
}