services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: unless-stopped
    network_mode: "host"
    command: [ "--config", "/etc/livekit/config.yml" ]
    volumes:
      - ../config.yml:/etc/livekit/config.yml:ro
    depends_on:
      - redis_livekit

  redis_livekit:
    container_name: redis_livekit
    image: redis:7
    restart: unless-stopped
    networks:
      - live-network
    ports:
      - "127.0.0.1:6380:6379"

  livekit-agent:
    image: ejjem/s14p11a704:livekit-agent
    container_name: livekit-agent
    restart: unless-stopped
    networks:
      - live-network
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - LIVEKIT_URL=http://host.docker.internal:8000
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_REDIS_URL=redis://redis_livekit:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["dev"]
    depends_on:
      - livekit
      - redis_livekit

  livekit-egress:
    image: livekit/egress:latest
    container_name: livekit-egress
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - live-network
      - app-network
    volumes:
      - ./egress/config.yml:/etc/egress/egress_config.yml:ro
    environment:
      - LIVEKIT_URL=http://host.docker.internal:8000
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - EGRESS_REDIS_URL=redis://redis_livekit:6379
      - EGRESS_S3_ENDPOINT=${CLOUDFLARE_ENDPOINT}
      - EGRESS_S3_ACCESS_KEY=${CLOUDFLARE_ACCESS_KEY}
      - EGRESS_S3_SECRET=${CLOUDFLARE_SECRET_KEY}
      - EGRESS_S3_BUCKET=${CLOUDFLARE_BUCKET}
    depends_on:
      - livekit
      - redis_livekit
    command:
      ["--config", "/etc/egress/egress_config.yml"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  live-network:
    external: true
  app-network:
    external: true