port: 8000 # Signaling 포트

rtc:
  tcp_port: 8001
  port_range_start: 20000
  port_range_end: 21000
  use_external_ip: true

keys:
  devkeys: secret_itsjusttestkeyiwilllchangethisassoonaspossible

redis:
  address: localhost:6379
turn:
  enabled: true
  udp_port: 8002
