services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: unless-stopped

    command: ["--config", "/etc/livekit/config.yml"]

    volumes:
      - ../livekit/config.yml:/etc/livekit/config.yml:ro
    ports:
      # signaling (ws/wss)
      - "8001:7880"
      # WebRTC TCP fallback
      - "8000:7881"
      # WebRTC media (UDP Range) - 대규모 접속 대응
      - "20000-30000:50000-60000/udp"
