services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro

      - certbot-www:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h;
      done"
    restart: unless-stopped

volumes:
  certbot-www:
  letsencrypt:
