services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      # (1) 레포에서 관리되는 nginx 설정(conf.d)
      - /home/ubuntu/app/infra/infra-repo/infra/nginx/conf.d:/etc/nginx/conf.d:ro

      # (2) 운영 데이터: ACME challenge (webroot)
      - /home/ubuntu/app/infra-runtime/certbot/www:/var/www/certbot:ro

      # (3) 운영 데이터: 인증서 저장소
      - /home/ubuntu/app/infra-runtime/certbot/conf:/etc/letsencrypt:ro

    restart: unless-stopped
