host: ${LIVEKIT_URL}
api_key: ${LIVEKIT_API_KEY}
api_secret: ${LIVEKIT_API_SECRET}

redis:
  address: ${EGRESS_REDIS_URL}

logging:
  level: info

options:
  video_codec: H264_MAIN
  video_bitrate: 2500
  framerate: 30
  width: 1280
  height: 720
  audio_codec: AAC
  audio_bitrate: 128
  audio_frequency: 44100
