spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: on
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakaopay:
  base-url: https://open-api.kakaopay.com
  cid: ${KAKAOPAY_CLIENT_ID}
  secret-key: ${KAKAOPAY_SECRET_KEY}
  redirect-urls:
    approval: http://localhost:8080/swagger-ui/index.html
    cancel: http://localhost:8080/swagger-ui/index.html
    fail: http://localhost:8080/swagger-ui/index.html

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR


cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_ENDPOINT}
    bucket: ${CLOUDFLARE_BUCKET}
    access-key: ${CLOUDFLARE_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION} # 14D

livekit:
  url: ${LIVEKIT_URL}
  api-key: ${LIVEKIT_API_KEY}
  secret: ${LIVEKIT_API_SECRET}